# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "k8smaster" do |node|
  
    node.vm.box               = "generic/ubuntu2004" 
    node.vm.box_check_update  = false
    node.vm.box_version       = "3.2.10"
    node.vm.hostname          = "k8smaster.example.com"

    node.vm.network "private_network", ip: "172.16.16.100"

    config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

    config.ssh.forward_agent = true
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    # config.ssh.insert_key = 'true'
  
    node.vm.provider :virtualbox do |v|
      v.name    = "k8smaster"
      v.memory  = 2048
      v.cpus    =  2
    end
  
    node.vm.provider :libvirt do |v|
      v.memory  = 2048
      v.nested  = true
      v.cpus    = 2
    end
  
    node.vm.provision "shell", path: "bootstrap_k8smaster.sh", privileged: true
  
  end


  # Kubernetes Worker Nodes
  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "k8sworker#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.2.10"
      node.vm.hostname          = "k8sworker#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"

      config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

      config.ssh.forward_agent = true
      config.ssh.username = 'vagrant'
      config.ssh.password = 'vagrant'
      # config.ssh.insert_key = 'true'
      
      node.vm.provider :virtualbox do |v|
        v.name    = "k8sworker#{i}"
        v.memory  = 1024
        v.cpus    = 1
      end

      node.vm.provider :libvirt do |v|
        v.memory  = 1024
        v.nested  = true
        v.cpus    = 1
      end

      node.vm.provision "shell", path: "bootstrap_k8sworker.sh", privileged: true

    end

  end

end
